### ISSUE TITLE
Failed to activate the atom-ide-datatip package

### ISSUE THREAD

**Issue by npdev453** [atom-community/atom-ide-datatip#65] opened 2020-04-18 13:59 UTC
[Enter steps to reproduce:]

1. just install 
2. ...

**Atom**: 1.46.0-beta0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [atom-ide-datatip](https://github.com/atom-ide-community/atom-ide-datatip) package 0.11.4

### Stack Trace

Failed to activate the atom-ide-datatip package

```
At service.addModifierProvider is not a function

TypeError: service.addModifierProvider is not a function
    at Activation.consumeDatatipService (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-definitions/lib/main.js:314:32)
    at /packages/atom-ide-ui/modules/nuclide-commons-atom/createPackage.js:64:34)
    at Provider.provide (~/resources/app/static/<embedded>:14:1119368)
    at ServiceHub.provide (~/resources/app/static/<embedded>:11:3279060)
    at Package.activateServices (~/resources/app/static/<embedded>:11:3287346)
    at Package.activateNow (~/resources/app/static/<embedded>:11:3284322)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (~/resources/app/static/<embedded>:11:1215907)
    at Emitter.emit (~/resources/app/static/<embedded>:11:1217348)
    at PackageManager.triggerDeferredActivationHooks (~/resources/app/static/<embedded>:11:383144)
    at activatePromise.Promise.all.then (~/resources/app/static/<embedded>:11:381895)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-datatip 0.11.4 
atom-ide-markdown-service 1.2.4 
atom-ide-ui 0.13.0 
atom-ide-vue 1.3.1 
busy-signal 2.0.1 
```

**Comment by Belar** [comment] 2020-04-20 19:18
Thanks for the report, based on the stack trace, it's a compatibility issue in `atom-ide-ui`. Looks like a duplicate of https://github.com/atom-ide-community/atom-ide-datatip/issues/1

**Closed as completed** 2020-05-10 17:33 UTC
